In [3]:
from sentence_transformers import SentenceTransformer

import faiss

import numpy as np

import google.generativeai as genai

In [4]:

genai.configure(api_key="AIzaSyAS1UXcdMsEwuqTqTWuhCGDDq2607haujE")

model = genai.GenerativeModel("gemini-2.5-flash")


### Load embedding model

In [19]:
embedder = SentenceTransformer('all-mpnet-base-v2')

embedder

SentenceTransformer(
  (0): Transformer({'max_seq_length': 384, 'do_lower_case': False}) with Transformer model: MPNetModel 
  (1): Pooling({'word_embedding_dimension': 768, 'pooling_mode_cls_token': False, 'pooling_mode_mean_tokens': True, 'pooling_mode_max_tokens': False, 'pooling_mode_mean_sqrt_len_tokens': False, 'pooling_mode_weightedmean_tokens': False, 'pooling_mode_lasttoken': False, 'include_prompt': True})
  (2): Normalize()
)

### knowledge base docs

In [20]:
docs = [
    "Our company policy states that all employees must complete security training annually.",
    "The employee onboarding process takes approximately two weeks.",
    "You can reset your company email password via the IT support portal.",
    "Remote work is allowed up to 3 days per week with manager approval."
]

### Step 1: Embed documents

In [21]:

doc_embeddings = embedder.encode(docs)

doc_embeddings

array([[ 0.00566584,  0.05591124,  0.01002902, ...,  0.00674632,
         0.00280357, -0.01628686],
       [ 0.01020954, -0.01653448, -0.01218479, ...,  0.00068556,
        -0.09472698, -0.01186781],
       [-0.04256048,  0.0348694 ,  0.00450059, ..., -0.0459226 ,
        -0.027772  ,  0.01081706],
       [ 0.00095095, -0.02865156, -0.00998841, ...,  0.03160292,
        -0.10529932,  0.00957792]], dtype=float32)

### Step 2: Create FAISS index

In [22]:

dimension = doc_embeddings.shape[1]

dimension

768

In [23]:

doccc = doc_embeddings.shape[0]
doccc

4

In [24]:

index = faiss.IndexFlatIP(dimension)

index.add(np.array(doc_embeddings).astype('float32'))


In [25]:

index

<faiss.swigfaiss_avx2.IndexFlatIP; proxy of <Swig Object of type 'faiss::IndexFlatIP *' at 0x000001B219537810> >

In [26]:

def answer_question(question):
  
    # Embed question
    q_emb = embedder.encode([question]).astype('float32')

    # Retrieve top 2 docs
    D, I = index.search(q_emb, k=2)

    print(I)
    print(D)
   
    retrieved_docs = [docs[i] for i in I[0]]

    # Prepare prompt for Gemini
    context = "\n\n".join(retrieved_docs)
    
    prompt = f"""
    You are a helpful assistant answering questions based on the following company documents:

    {context}

    Question: {question}

    Provide a concise, accurate answer.
    """
    # Generate answer
    response = model.generate_content(prompt)
    return response.text
    

### query

In [27]:

question = "How do I reset my email password?"

answer = answer_question(question)

print("Answer:", answer)


[[2 0]]
[[0.6316932  0.03873719]]
Answer: You can reset your company email password via the IT support portal.


| Rank | Document Index | Document                                                                                 |
| ---- | -------------- | ---------------------------------------------------------------------------------------- |
| 1    | 2              | "You can reset your company email password via the IT support portal."                   |
| 2    | 0              | "Our company policy states that all employees must complete security training annually." |


| Document | Distance | Similarity         |
| -------- | -------- | ------------------ |
| Doc 2    | 0.5607   | Highest similarity |
| Doc 0    | 1.8703   | Lower similarity   |


User Question
     │
     ▼
Embedding Model
(all-MiniLM-L6-v2)
     │
     ▼
Query Vector
     │
     ▼
FAISS Search
     │
     ▼
Top Results
Doc 2 (distance 0.56)
Doc 0 (distance 1.87)
     │
     ▼
Send Context + Question
to Gemini
     │
     ▼
Generated Answer
"Via the IT support portal"