In [1]:
import numpy as np
array = np.array([10, 2, 9, -1])

sortedIndices = np.argsort(array)

print('Index of sorted array:', sortedIndices)

Index of sorted array: [3 1 2 0]


In [2]:
print('Sorted array:', array[sortedIndices])

Sorted array: [-1  2  9 10]


In [3]:
import numpy as np

array = np.array(['Apple', 'apple', 'Ball', 'Cat'])

sortedIndices = np.argsort(array)

print('Index of sorted array: ', sortedIndices)
print('Sorted array: ',array[sortedIndices])

Index of sorted array:  [0 2 3 1]
Sorted array:  ['Apple' 'Ball' 'Cat' 'apple']


In [4]:
import numpy as np

datatype = [('name', 'U7'), ('age', int), ('height', int)]
people = [
            ('Alice', 35, 170), ('Bob', 30, 180), ('Charlie', 25, 175)
         ]
array = np.array(people, dtype = datatype)
array

array([('Alice', 35, 170), ('Bob', 30, 180), ('Charlie', 25, 175)],
      dtype=[('name', '<U7'), ('age', '<i4'), ('height', '<i4')])

In [6]:
print(array['name'])    
print(array['age'])     
print(array['height']) 

['Alice' 'Bob' 'Charlie']
[35 30 25]
[170 180 175]


In [7]:
array2 = np.argsort(array, order = 'age')

print('Index of sorted array:\n', array2)
print('Sorted array:\n', array[array2])

Index of sorted array:
 [2 1 0]
Sorted array:
 [('Charlie', 25, 175) ('Bob', 30, 180) ('Alice', 35, 170)]


In [8]:
import numpy as np
array1 = np.array([10, 12, 14, 11, 5])

maxIndex= np.argmax(array1)

print(maxIndex)

2


In [ ]:
import numpy as np

array = np.array(['A', 'B', 'a', 'D', 'C'])

maxIndex = np.argmax(array)

print(maxIndex)

In [ ]:
import numpy as np
array1 = np.array([10, 12, 14, 11, 5])

minIndex = np.argmin(array1)

print(minIndex)

In [ ]:
import numpy as np

originalArray = np.array([1, 0, 0, 4, -5])

result = np.argwhere(originalArray )

print(result)