In [3]:
lst = [10,20,30,40]
for i in range(len(lst)):
    print(i,"--->",id(lst[i]))

0 ---> 140703459121880
1 ---> 140703459122200
2 ---> 140703459122520
3 ---> 140703459122840


In [4]:
import numpy as np
lst = np.array(lst)
for i in range(len(lst)):
    print(i,"--->",id(lst[i]))

0 ---> 1851185179792
1 ---> 1851185179376
2 ---> 1851185179792
3 ---> 1851185179376


In [10]:
import numpy as np
a = np.arange(3*3).reshape(3,3)
print("content of a \n",a)

content of a 
 [[0 1 2]
 [3 4 5]
 [6 7 8]]


In [11]:
a[0]

array([0, 1, 2])

In [12]:
a[0,0]

np.int64(0)

In [13]:
a[0:3]

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [14]:
a[0:3,0:]

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [16]:
a[1,1:2]

array([4])

In [23]:
a= np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10],[11,12,13,14,15]])

print(a[0:2, 2])

[3 8]


In [24]:
a[0:5]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [19]:
a[3:]

array([], shape=(0, 5), dtype=int64)

In [25]:
a[:][2:]

array([[11, 12, 13, 14, 15]])

In [26]:
a = np.arange(1,13).reshape(3,4)
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [27]:
a[2:]

array([[ 9, 10, 11, 12]])

In [28]:
a[2:1]

array([], shape=(0, 4), dtype=int64)

In [29]:
a[2:3]

array([[ 9, 10, 11, 12]])

In [30]:
a[2:2]

array([], shape=(0, 4), dtype=int64)

In [31]:
a[2:0]

array([], shape=(0, 4), dtype=int64)

In [32]:
a[2:4]

array([[ 9, 10, 11, 12]])

In [33]:
a[][3]

SyntaxError: invalid syntax (3855398949.py, line 1)

In [34]:
a[0][0]

np.int64(1)

In [35]:
a[0:2][1:3]

array([[5, 6, 7, 8]])