In [1]:
import numpy as np

In [2]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
arr

array([2, 1, 5, 3, 7, 4, 6, 8])

In [3]:
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [4]:
brr = arr.reshape(4, 2)
brr

array([[2, 1],
       [5, 3],
       [7, 4],
       [6, 8]])

In [ ]:
np.reshape(arr, newshape=(1, 8), order='C')

### How to convert a 1D array into a 2D array (how to add a new axis to an array)

In [5]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])

print(arr.shape, arr.ndim)
print(arr)

(8,) 1
[2 1 5 3 7 4 6 8]


In [6]:
a2rr = arr[np.newaxis, :]

print(a2rr.shape,a2rr.ndim)
print(a2rr)

(1, 8) 2
[[2 1 5 3 7 4 6 8]]


arr[np.newaxis, :] adds a new axis (dimension) to the array, converting it from shape (8,) to (1, 8).

         This turns the 1D array into a 2D row vector (a matrix with 1 row and 8 columns).

a2rr.shape is now (1, 8) because it has 1 row and 8 columns.

a2rr.ndim is 2 because the array is now two-dimensional.

In [7]:
c2rr = a2rr[:, np.newaxis]

print(c2rr.shape,c2rr.ndim)
print(c2rr)

(1, 1, 8) 3
[[[2 1 5 3 7 4 6 8]]]


Using np.newaxis will increase the dimensions of your array by one dimension when used once. 

This means that a 1D array will become a 2D array, a 2D array will become a 3D array, and so on.

You can explicitly convert a 1D array with either a row vector or a column vector using np.newaxis. 

You can also expand an array by inserting a new axis at a specified position with np.expand_dims.

In [8]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape,a.ndim

((6,), 1)

In [9]:
b = np.expand_dims(a, axis=1)
b.shape,b.ndim

((6, 1), 2)

In [10]:
c = np.expand_dims(a, axis=0)
c.shape,c.ndim

((1, 6), 2)

### Conditions

In [11]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [12]:
print(a[a < 5])

[1 2 3 4]


In [13]:
five_up = (a >= 5)
print(a[five_up])

[ 5  6  7  8  9 10 11 12]


In [14]:
divisible_by_2 = a[a%2==0]
print(divisible_by_2)

[ 2  4  6  8 10 12]


In [15]:
c = a[(a > 2) & (a < 11)]
print(c)

[ 3  4  5  6  7  8  9 10]


In [16]:
five_up = (a > 5) | (a == 5)
print(five_up)

[[False False False False]
 [ True  True  True  True]
 [ True  True  True  True]]


In [ ]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

In [ ]:
b = np.nonzero(a < 5)
print(b)

You can use np.nonzero() to print the indices of elements that are, for example, less than 5:

### Save your arrays with NumPy’s 

In [22]:
x = np.arange(10)
y = x ** 2
print(x)
print(y)

[0 1 2 3 4 5 6 7 8 9]
[ 0  1  4  9 16 25 36 49 64 81]


In [23]:
np.savez("x_y-squared.npz", x_axis=x, y_axis=y)

In [24]:
load_xy = np.load("x_y-squared.npz")

print(load_xy.files)

['x_axis', 'y_axis']


In [25]:
x = load_xy["x_axis"]
y = load_xy["y_axis"]
print(x)
print(y)

[0 1 2 3 4 5 6 7 8 9]
[ 0  1  4  9 16 25 36 49 64 81]


### saving to human-readable csv

np.block: this function appends arrays together into a 2D array

np.newaxis: this function forces the 1D array into a 2D column vector with 10 rows and 1 column.

In [26]:
array_out = np.block([x[:, np.newaxis], y[:, np.newaxis]])

print("the output array has shape ", array_out.shape)
print(array_out)

the output array has shape  (10, 2)
[[ 0  0]
 [ 1  1]
 [ 2  4]
 [ 3  9]
 [ 4 16]
 [ 5 25]
 [ 6 36]
 [ 7 49]
 [ 8 64]
 [ 9 81]]


In [27]:
np.savetxt("x_y-squared.csv", X=array_out, header="x, y", delimiter=",")

In [29]:
load_xy = np.loadtxt("x_y-squared.csv", delimiter=",")

In [30]:
load_xy.shape

(10, 2)

In [31]:
x = load_xy[:, 0]
y = load_xy[:, 1]
print(x)
print(y)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[ 0.  1.  4.  9. 16. 25. 36. 49. 64. 81.]


### Flatten

The flatten() method flattens a NumPy array without changing its data.

In [17]:
import numpy as np

array1 = np.array([[0, 1], 
                   [2, 3]])
array2 = array1.flatten()
print(array2)

[0 1 2 3]


In [18]:
import numpy as np

array1 = np.array([[[0, 1], 
                    [2, 3]],
                   [[4, 5], 
                    [6, 7]]])

# flatten the array row-wise
array2 = array1.flatten(order = 'C')

print("C:",array2)

# flatten the array column-wise
array3 = array1.flatten( order = 'F')

print("F:",array3)

# flatten the array to original array's order
array4 = array1.flatten(order = 'A')

print("A:",array2)

# flatten the array  in the order they occur in memory
array5 = array1.flatten(order = 'K')

print("K:",array3)


C: [0 1 2 3 4 5 6 7]
F: [0 4 2 6 1 5 3 7]
A: [0 1 2 3 4 5 6 7]
K: [0 4 2 6 1 5 3 7]


### ravel() 

The ravel() method flattens a NumPy array without changing its data.

In [19]:
import numpy as np

array1 = np.array([[0, 1], [2, 3]])

array2 = np.ravel(array1)

print(array2)

[0 1 2 3]


### key differences between flatten() and ravel() are

flatten() is an ndarray object method 

whereas ravel() is a library-level function.

In [20]:
import numpy as np

array1 = np.array([[1, 2],
                   [3, 4]])

array2 = array1.flatten()
array3 = np.ravel(array1)

print(array2)
print(array3)

[1 2 3 4]
[1 2 3 4]
